// AutolinkedNativeModules.g.cpp contents generated by "npx @react-native-community/cli autolink-windows"
// MODIFIED for Fabric mode - use factory function from DLL instead of WinRT projection
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

#include <winrt/Windows.Foundation.Collections.h>

// Forward declare the factory function exported from DateTimePicker.dll
extern "C" __declspec(dllimport) winrt::Microsoft::ReactNative::IReactPackageProvider __stdcall CreateDateTimePickerPackageProvider() noexcept;

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // Call the factory function from DateTimePicker.dll
    packageProviders.Append(CreateDateTimePickerPackageProvider());
}

}
