
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen) 
 * and copied to the cpp directory to add custom state and set shadow node trait as a LeafYogaNode.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include "ShadowNodes.h"

namespace facebook {
namespace react {

extern const char RNDateTimePickerComponentName[] = "RNDateTimePicker";

} // namespace react
} // namespace facebook
