require_relative '../../node_modules/react-native-test-app/test_app'

workspace 'date-time-picker-example.xcworkspace'

# Flipper causes the build to fail on release when fabric is enabled
# https://github.com/facebook/react-native/issues/33764

use_flipper! false unless ENV['ENABLE_FLIPPER']

use_test_app!
