// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace DateTimePicker {

    [default_interface]
    runtimeclass DateTimePickerView : Windows.UI.Xaml.Controls.CalendarDatePicker {
        DateTimePickerView();
    };

    [default_interface]
    runtimeclass TimePickerView : Windows.UI.Xaml.Controls.TimePicker {
        TimePickerView();
    };
}
