name: release-please

on:
  push:
    branches:
      - master

permissions:
  id-token: write  # Required for kOIDC
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          yarn install --immutable
          yarn plugin:build
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          npm install -g npm@latest
          npm publish
        if: ${{ steps.release.outputs.release_created }}
